version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: travel_planner_postgres
    environment:
      POSTGRES_DB: travel_planner_dev
      POSTGRES_USER: travel_planner
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travel_planner -d travel_planner_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: